### PR TITLE
login signup routes, some sql queries

### PR DESCRIPTION
**Pull request by simk209**
some login/signup routes, and some sql queries + sql model connection

### CODE REVIEW

**Review by EricDalio — APPROVED** [review]
Great work!

**Review by alanaherlands — APPROVED** [review]
Nice job!

**Review by ericmrennie — APPROVED** [review]
Nice routes and queries!

**Review by EivindDelFierro — APPROVED** [review]
Deleted package-lock.json and updated server/controllers/auth.js. LGTM!

**Pull request merged**
